<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agensi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Agensi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $agensi = $this->Agensi_model->get_all();

        $data = array(
            'agensi_data' => $agensi
        );

        $this->load->view('agensi/agensi_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Agensi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'aid' => $row->aid,
		'nama' => $row->nama,
		'penerangan' => $row->penerangan,
	    );
            $this->load->view('agensi/agensi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('agensi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('agensi/create_action'),
	    'aid' => set_value('aid'),
	    'nama' => set_value('nama'),
	    'penerangan' => set_value('penerangan'),
	);
        $this->load->view('agensi/agensi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'penerangan' => $this->input->post('penerangan',TRUE),
	    );

            $this->Agensi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('agensi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Agensi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('agensi/update_action'),
		'aid' => set_value('aid', $row->aid),
		'nama' => set_value('nama', $row->nama),
		'penerangan' => set_value('penerangan', $row->penerangan),
	    );
            $this->load->view('agensi/agensi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('agensi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('aid', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'penerangan' => $this->input->post('penerangan',TRUE),
	    );

            $this->Agensi_model->update($this->input->post('aid', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('agensi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Agensi_model->get_by_id($id);

        if ($row) {
            $this->Agensi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('agensi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('agensi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');
	$this->form_validation->set_rules('penerangan', 'penerangan', 'trim|required');

	$this->form_validation->set_rules('aid', 'aid', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Agensi.php */
/* Location: ./application/controllers/Agensi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-03 01:12:27 */
/* http://harviacode.com */