<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Awam extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Awam_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $awam = $this->Awam_model->get_all();

        $data = array(
            'awam_data' => $awam
        );

        $this->load->view('awam/awam_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Awam_model->get_by_id($id);
        if ($row) {
            $data = array(
		'awid' => $row->awid,
		'nama' => $row->nama,
		'penerangan' => $row->penerangan,
	    );
            $this->load->view('awam/awam_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('awam'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('awam/create_action'),
	    'awid' => set_value('awid'),
	    'nama' => set_value('nama'),
	    'penerangan' => set_value('penerangan'),
	);
        $this->load->view('awam/awam_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'penerangan' => $this->input->post('penerangan',TRUE),
	    );

            $this->Awam_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('awam'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Awam_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('awam/update_action'),
		'awid' => set_value('awid', $row->awid),
		'nama' => set_value('nama', $row->nama),
		'penerangan' => set_value('penerangan', $row->penerangan),
	    );
            $this->load->view('awam/awam_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('awam'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('awid', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'penerangan' => $this->input->post('penerangan',TRUE),
	    );

            $this->Awam_model->update($this->input->post('awid', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('awam'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Awam_model->get_by_id($id);

        if ($row) {
            $this->Awam_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('awam'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('awam'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');
	$this->form_validation->set_rules('penerangan', 'penerangan', 'trim|required');

	$this->form_validation->set_rules('awid', 'awid', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Awam.php */
/* Location: ./application/controllers/Awam.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-03 16:10:13 */
/* http://harviacode.com */