<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Drop_kategori extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Drop_kategori_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $drop_kategori = $this->Drop_kategori_model->get_all();

        $data = array(
            'drop_kategori_data' => $drop_kategori
        );

        $this->load->view('drop_kategori/drop_kategori_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Drop_kategori_model->get_by_id($id);
        if ($row) {
            $data = array(
		'dkid' => $row->dkid,
		'Kategori' => $row->Kategori,
	    );
            $this->load->view('drop_kategori/drop_kategori_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('drop_kategori'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('drop_kategori/create_action'),
	    'dkid' => set_value('dkid'),
	    'Kategori' => set_value('Kategori'),
	);
        $this->load->view('drop_kategori/drop_kategori_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'Kategori' => $this->input->post('Kategori',TRUE),
	    );

            $this->Drop_kategori_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('drop_kategori'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Drop_kategori_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('drop_kategori/update_action'),
		'dkid' => set_value('dkid', $row->dkid),
		'Kategori' => set_value('Kategori', $row->Kategori),
	    );
            $this->load->view('drop_kategori/drop_kategori_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('drop_kategori'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('dkid', TRUE));
        } else {
            $data = array(
		'Kategori' => $this->input->post('Kategori',TRUE),
	    );

            $this->Drop_kategori_model->update($this->input->post('dkid', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('drop_kategori'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Drop_kategori_model->get_by_id($id);

        if ($row) {
            $this->Drop_kategori_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('drop_kategori'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('drop_kategori'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('Kategori', 'kategori', 'trim|required');

	$this->form_validation->set_rules('dkid', 'dkid', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Drop_kategori.php */
/* Location: ./application/controllers/Drop_kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-03 16:10:13 */
/* http://harviacode.com */