<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Drop_level extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Drop_level_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $drop_level = $this->Drop_level_model->get_all();

        $data = array(
            'drop_level_data' => $drop_level
        );

        $this->load->view('drop_level/drop_level_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Drop_level_model->get_by_id($id);
        if ($row) {
            $data = array(
		'lid' => $row->lid,
		'level' => $row->level,
	    );
            $this->load->view('drop_level/drop_level_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('drop_level'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('drop_level/create_action'),
	    'lid' => set_value('lid'),
	    'level' => set_value('level'),
	);
        $this->load->view('drop_level/drop_level_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'level' => $this->input->post('level',TRUE),
	    );

            $this->Drop_level_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('drop_level'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Drop_level_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('drop_level/update_action'),
		'lid' => set_value('lid', $row->lid),
		'level' => set_value('level', $row->level),
	    );
            $this->load->view('drop_level/drop_level_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('drop_level'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('lid', TRUE));
        } else {
            $data = array(
		'level' => $this->input->post('level',TRUE),
	    );

            $this->Drop_level_model->update($this->input->post('lid', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('drop_level'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Drop_level_model->get_by_id($id);

        if ($row) {
            $this->Drop_level_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('drop_level'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('drop_level'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('level', 'level', 'trim|required');

	$this->form_validation->set_rules('lid', 'lid', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Drop_level.php */
/* Location: ./application/controllers/Drop_level.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-03 16:10:13 */
/* http://harviacode.com */