<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_model extends CI_Model
{

    public $table = 'surat';
    public $id = 'sid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('sid', $q);
	$this->db->or_like('tarikhTerima', $q);
	$this->db->or_like('Jenis', $q);
	$this->db->or_like('awam', $q);
	$this->db->or_like('agensi', $q);
	$this->db->or_like('bahagian', $q);
	$this->db->or_like('individu', $q);
	$this->db->or_like('jawatan', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('rujukanSurat', $q);
	$this->db->or_like('RingkasanKandungan', $q);
	$this->db->or_like('tarikhSurat', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('Imbas', $q);
	$this->db->or_like('pendaftar', $q);
	$this->db->or_like('tarikhKemasukkan', $q);
	$this->db->or_like('TindakanTotal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('sid', $q);
	$this->db->or_like('tarikhTerima', $q);
	$this->db->or_like('Jenis', $q);
	$this->db->or_like('awam', $q);
	$this->db->or_like('agensi', $q);
	$this->db->or_like('bahagian', $q);
	$this->db->or_like('individu', $q);
	$this->db->or_like('jawatan', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('rujukanSurat', $q);
	$this->db->or_like('RingkasanKandungan', $q);
	$this->db->or_like('tarikhSurat', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('Imbas', $q);
	$this->db->or_like('pendaftar', $q);
	$this->db->or_like('tarikhKemasukkan', $q);
	$this->db->or_like('TindakanTotal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Surat_model.php */
/* Location: ./application/models/Surat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-03 16:10:13 */
/* http://harviacode.com */